# Generated by Django 4.2.2 on 2023-07-03 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='to',
            new_name='media_to',
        ),
    ]
