# Generated by Django 4.2.2 on 2023-07-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='context_type',
            new_name='content_type',
        ),
    ]
