# Generated by Django 4.2.2 on 2023-06-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0014_remove_role_user'),
        ('user', '0002_alter_user_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Role',
            field=models.ManyToManyField(to='permissions.role'),
        ),
    ]
