# Generated by Django 4.2.2 on 2023-06-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Role',
            new_name='roles',
        ),
    ]
