# Generated by Django 4.2.2 on 2023-06-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_role_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
