# Generated by Django 4.2.2 on 2023-07-14 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_resetcodeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcodeuser',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 9, 43, 10, 219708, tzinfo=datetime.timezone.utc)),
        ),
    ]
