# Generated by Django 4.2.2 on 2023-07-19 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_resetcodeuser_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcodeuser',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 20, 8, 43, 15, 196265, tzinfo=datetime.timezone.utc)),
        ),
    ]
