# Generated by Django 4.2.2 on 2023-07-25 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_resetcodeuser_expired_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcodeuser',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 3, 10, 28, 29999, tzinfo=datetime.timezone.utc)),
        ),
    ]
