# Generated by Django 4.2.2 on 2023-06-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permissions', '0004_alter_permission_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
