# Generated by Django 4.2.2 on 2023-06-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0009_alter_permission_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='code_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
