# Generated by Django 4.2.2 on 2023-06-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0013_alter_permission_created_by_alter_role_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
    ]
