# Generated by Django 4.2.2 on 2023-07-03 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0004_alter_subcriber_time_tracking_id_and_more'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subcriber_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.subcriber'),
        ),
    ]
