# Generated by Django 4.2.2 on 2023-07-03 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trackingapp.custom_middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_alter_notification_subcriber_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='subcriber_id',
            new_name='subcriber',
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(default=trackingapp.custom_middleware.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
