# Generated by Django 4.2.2 on 2023-06-29 07:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trackingapp.custom_middleware
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('release', models.CharField(max_length=128)),
                ('task_id', models.CharField(max_length=128)),
                ('task_link', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField()),
                ('status', models.TextField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('IN_REVIEW', 'IN_REVIEW'), ('RESOLVED', 'RESOLVED'), ('DEV_TEST', 'DEV_TEST'), ('QC_TEST', 'QC_TEST'), ('DONE', 'DONE')], default='TODO', max_length=128)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(default=trackingapp.custom_middleware.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
