# Generated by Django 4.2.2 on 2023-07-03 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0002_alter_timetracking_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='status',
            field=models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('IN_REVIEW', 'IN_REVIEW'), ('RESOLVED', 'RESOLVED'), ('DEV_TEST', 'DEV_TEST'), ('QC_TEST', 'QC_TEST'), ('DONE', 'DONE')], default='TODO', max_length=128),
        ),
        migrations.CreateModel(
            name='Subcriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('time_tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.timetracking', unique=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Histody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('change_detection', models.JSONField()),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('time_tracking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.timetracking')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
