# Generated by Django 4.2.2 on 2023-07-03 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0003_timetracking_is_deleted_alter_timetracking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriber',
            name='time_tracking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.timetracking'),
        ),
        migrations.AlterField(
            model_name='subcriber',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subcriber',
            unique_together={('time_tracking_id', 'user_id')},
        ),
    ]
