# Generated by Django 4.2.2 on 2023-07-03 07:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0004_alter_subcriber_time_tracking_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Histody',
            new_name='History',
        ),
    ]
