# Generated by Django 4.2.2 on 2023-07-03 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trackingapp.custom_middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0005_rename_histody_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='time_tracking_id',
            new_name='time_tracking',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subcriber',
            old_name='time_tracking_id',
            new_name='time_tracking',
        ),
        migrations.RenameField(
            model_name='subcriber',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='history',
            name='created_by',
            field=models.ForeignKey(default=trackingapp.custom_middleware.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subcriber',
            name='created_by',
            field=models.ForeignKey(default=trackingapp.custom_middleware.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='created_by',
            field=models.ForeignKey(default=trackingapp.custom_middleware.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
