# Generated by Django 4.2.2 on 2023-07-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0006_rename_time_tracking_id_history_time_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
