# Generated by Django 4.2.2 on 2023-07-10 03:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trackingapp.custom_middleware
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0009_rename_user_id_timetracking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='subcriber',
            name='object_type',
            field=models.CharField(choices=[('RELEASE', 'RELEASE'), ('TASK', 'TASK')], default='TASK', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcriber',
            name='time_tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_tracking.timetracking'),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('release', models.CharField(max_length=128)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE')], default='TODO', max_length=128)),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=trackingapp.custom_middleware.get_current_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subcriber',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='time_tracking.release'),
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracking.release'),
        ),
    ]
