# Generated by Django 4.2.2 on 2023-07-13 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0011_workflow_workflowstep_condition'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcriber',
            unique_together=set(),
        ),
    ]
