# Generated by Django 4.2.2 on 2023-07-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0012_alter_subcriber_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='workflow',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
